server:
  port: 8088
  #context-path: /
  tomcat:
        basedir: /root/time_line/temp

spring:
  application:
    name: TL
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  aop:
    proxy-target-class: true
    auto: true
  data:
      solr:
        host: http://127.0.0.1:8983/solr

      elasticsearch:
        cluster-name: my-application
        cluster-nodes: 188.131.221.99:9300

  elasticsearch:
    jest:
      uris: http://188.131.221.99:9200

  redis:
    host: 188.131.221.99
    port: 6379
    timeout: 10

logging:
  config: classpath:log4j2.xml
log4j:
  isThreadContextMapInheritable: true
AsyncLogger:
  RingBufferSize: 1048576

disruptor:
  ringBufferSize: 2097152
  timeout: 6000
  waitStrategy: TIMEOUT

token:
  expire:
    seconds: 7200
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)
---
#内测环境配置
spring:
  profiles: test
  #mysql配置
  datasource:
    name: tbc_common
    url: jdbc:mysql://localhost:3306/time_line?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    spring.datasource.filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml


